AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3BucketName:
  Type: String
  Default: MyBucket
  Description: Name of the S3 bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3BucketName
                - /*
      Bucket: !Ref S3BucketName
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - !Ref S3BucketName
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - !Ref S3BucketName
          - DomainName
    Description: Name of S3 bucket to hold website content
