name: "Deploy s3-lambda CFT"
on: 
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v2 
    - uses: mgenteluci/cloudformation-deploy-action@v1.4.0  
      env:
        TEMPLATE: 'template.yml'
        AWS_STACK_NAME: 'stack-s3-lambda-balti'
        AWS_BUCKET_PREFIX: stacks/lambdas3
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
    
